# Generated by Django 5.0.6 on 2024-07-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstaff',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
