# Generated by Django 5.0.6 on 2024-07-28 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing_system', '0002_bankstaff_email_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TELLER', 'Teller Transactions'), ('CSO', 'CSO Transactions')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='queueentry',
            name='transaction_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='queuing_system.transactiontype'),
        ),
    ]
