# Generated by Django 5.0.6 on 2024-07-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuing_system', '0003_transactiontype_queueentry_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstaff',
            name='password',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
